// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Vault struct {
	ID        pgtype.UUID
	Salt      string
	CreatedAt pgtype.Timestamp
}

type VaultEntry struct {
	ID         pgtype.UUID
	Ciphertext string
	Nonce      string
	Website    string
	Label      string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	VaultID    pgtype.UUID
}
