// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllVaults = `-- name: GetAllVaults :many
select id, salt, created_at
from vault
`

func (q *Queries) GetAllVaults(ctx context.Context) ([]Vault, error) {
	rows, err := q.db.Query(ctx, getAllVaults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vault
	for rows.Next() {
		var i Vault
		if err := rows.Scan(&i.ID, &i.Salt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryByWebsite = `-- name: GetEntryByWebsite :one
select id, ciphertext, nonce, website, label, created_at, updated_at, vault_id
from vault_entry
where website = $1
`

func (q *Queries) GetEntryByWebsite(ctx context.Context, website string) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, getEntryByWebsite, website)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.Ciphertext,
		&i.Nonce,
		&i.Website,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VaultID,
	)
	return i, err
}

const insertVault = `-- name: InsertVault :one
insert into vault (salt)
values ($1)
returning id, salt, created_at
`

func (q *Queries) InsertVault(ctx context.Context, salt string) (Vault, error) {
	row := q.db.QueryRow(ctx, insertVault, salt)
	var i Vault
	err := row.Scan(&i.ID, &i.Salt, &i.CreatedAt)
	return i, err
}

const insertVaultEntry = `-- name: InsertVaultEntry :one
insert into vault_entry (ciphertext, nonce, website, label, vault_id)
values ($1, $2, $3, $4, $5)
returning id, ciphertext, nonce, website, label, created_at, updated_at, vault_id
`

type InsertVaultEntryParams struct {
	Ciphertext string
	Nonce      string
	Website    string
	Label      string
	VaultID    pgtype.UUID
}

func (q *Queries) InsertVaultEntry(ctx context.Context, arg InsertVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, insertVaultEntry,
		arg.Ciphertext,
		arg.Nonce,
		arg.Website,
		arg.Label,
		arg.VaultID,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.Ciphertext,
		&i.Nonce,
		&i.Website,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VaultID,
	)
	return i, err
}
